"""Creating new jobdata table

Revision ID: 66408f230880
Revises: 9961f09412d3
Create Date: 2018-04-21 11:20:56.484148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66408f230880'
down_revision = '9961f09412d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('num_rooms', sa.Integer(), nullable=True),
    sa.Column('wall_area', sa.Integer(), nullable=True),
    sa.Column('num_windows', sa.Integer(), nullable=True),
    sa.Column('num_doors', sa.Integer(), nullable=True),
    sa.Column('patchwork', sa.String(length=120), nullable=True),
    sa.Column('damages', sa.String(length=120), nullable=True),
    sa.Column('trim', sa.String(length=120), nullable=True),
    sa.Column('current_sheen', sa.String(length=120), nullable=True),
    sa.Column('current_color', sa.String(length=120), nullable=True),
    sa.Column('previous_paint', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobdata_customer'), 'jobdata', ['customer'], unique=False)
    op.drop_index('ix_job_data_customer', table_name='job_data')
    op.drop_table('job_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('customer', sa.VARCHAR(length=120), nullable=True),
    sa.Column('room_volume', sa.INTEGER(), nullable=True),
    sa.Column('wall_area', sa.INTEGER(), nullable=True),
    sa.Column('window_area', sa.INTEGER(), nullable=True),
    sa.Column('door_area', sa.INTEGER(), nullable=True),
    sa.Column('patchwork', sa.VARCHAR(length=120), nullable=True),
    sa.Column('damages', sa.VARCHAR(length=120), nullable=True),
    sa.Column('trim', sa.VARCHAR(length=120), nullable=True),
    sa.Column('current_sheen', sa.VARCHAR(length=120), nullable=True),
    sa.Column('current_color', sa.VARCHAR(length=120), nullable=True),
    sa.Column('previous_paint', sa.VARCHAR(length=120), nullable=True),
    sa.Column('other', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], [u'quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_data_customer', 'job_data', ['customer'], unique=False)
    op.drop_index(op.f('ix_jobdata_customer'), table_name='jobdata')
    op.drop_table('jobdata')
    # ### end Alembic commands ###
