"""First migrate

Revision ID: 9961f09412d3
Revises: 
Create Date: 2018-03-25 18:34:17.185612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9961f09412d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access_level', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_table('quoterequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('time_requested', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quoterequests_customer'), 'quoterequests', ['customer'], unique=False)
    op.create_index(op.f('ix_quoterequests_email'), 'quoterequests', ['email'], unique=False)
    op.create_table('job_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('room_volume', sa.Integer(), nullable=True),
    sa.Column('wall_area', sa.Integer(), nullable=True),
    sa.Column('window_area', sa.Integer(), nullable=True),
    sa.Column('door_area', sa.Integer(), nullable=True),
    sa.Column('patchwork', sa.String(length=120), nullable=True),
    sa.Column('damages', sa.String(length=120), nullable=True),
    sa.Column('trim', sa.String(length=120), nullable=True),
    sa.Column('current_sheen', sa.String(length=120), nullable=True),
    sa.Column('current_color', sa.String(length=120), nullable=True),
    sa.Column('previous_paint', sa.String(length=120), nullable=True),
    sa.Column('other', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_data_customer'), 'job_data', ['customer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_data_customer'), table_name='job_data')
    op.drop_table('job_data')
    op.drop_index(op.f('ix_quoterequests_email'), table_name='quoterequests')
    op.drop_index(op.f('ix_quoterequests_customer'), table_name='quoterequests')
    op.drop_table('quoterequests')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
